steps:

# if needed, produce a release candidate
# TODO: Somehow we need to figure out we already have a RC - currently we create the RC again becuase the merge commit is different
- id: 'produce-rc'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config'
  - 'cloudbuild-release-candidate.yaml'
  - '--substitutions'
  - 'COMMIT_SHA=$COMMIT_SHA'

# new revision for production service
- id: 'new-revision'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'basictoy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'

# send traffic to new revision in production service
- id: 'send-traffic'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'services'
  - 'update-traffic'
  - 'basictoy'
  - '--to-latest'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'