 steps:

 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA', '.']

 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA']

 # Deploy to a temp service
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'basictoy-$COMMIT_SHA'
   - '--image'
   - 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA'
   - '--region'
   - 'us-east4'
   - '--platform'
   - 'managed'
   - '--port'
   - '3000'
   - '--allow-unauthenticated'