steps:

# build the webapp container image
- id: 'build-webapp-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA', '.']
  waitFor: ['-']

# push the webapp container image to Container Registry
- id: 'push-webapp-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA']
  waitFor: ['build-webapp-image']

# build the integration load-tests container image
- id: 'build-load-test-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'load-tests/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/basictoy-lt:$COMMIT_SHA', '.']
  waitFor: ['-']

# push the integration load-tests container image to Container Registry
- id: 'push-load-test-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/basictoy-lt:$COMMIT_SHA']
  waitFor: ['build-load-test-image']

# Deploy webapp to a temp service
- id: 'deploy-temp-webapp-service'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'basictoy-$COMMIT_SHA', '--image', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA', '--region', 'us-east4', '--platform', 'managed', '--port', '3000', '--allow-unauthenticated']
  waitFor: ['push-webapp-image']

# capture the URL of the webapp service
- id: 'capture-service-url'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      gcloud run services describe basictoy-$COMMIT_SHA --platform managed --region us-east4 | grep Traffic | cut -c10-9999 > _webapp_service_url
      echo captured web app service url: $(cat _webapp_service_url)
  waitFor: ['deploy-temp-webapp-service']

# test if this can be done w/o pulling from gcr (should be in the workspace?)
# run integration load-tests
- id: 'run-load-tests'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      docker run -t gcr.io/$PROJECT_ID/basictoy-lt:$COMMIT_SHA locust --host $(cat _webapp_service_url) --no-web --clients 200 --hatch-rate 10 --run-time 120s
  waitFor: ['capture-service-url']

# delete temp web app service if lt was successful
- id: 'delete-temp-webapp-service'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services', 'delete', 'basictoy-$COMMIT_SHA', '--region', 'us-east4', '--platform', 'managed', '--quiet']
  waitFor: ['run-load-tests']