steps:

# build and do integration testing
- id: 'build-and-integration-test'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'builds', 
      'submit',
      '--config'
      'cloudbuild-integration.yaml',
      '--substitutions',
      'COMMIT_SHA=$COMMIT_SHA',
      '.'
  ]

# new revision for production service
- id: 'new-revision'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'basictoy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'

# send traffic to new revision in production service
- id: 'send-traffic'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'services'
  - 'update-traffic'
  - 'basictoy'
  - '--to-latest'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'



# build the container image
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA', '.']
# push the container image to Container Registry
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA']