steps:

# new revision for production service
- id: 'new-revision'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'basictoy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/basictoy:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'

# send traffic to new revision in production service
- id: 'send-traffic'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'services'
  - 'update-traffic'
  - 'basictoy'
  - '--to-latest'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'